#!/usr/bin/env bash
# shellcheck disable=2034,2155,2162

VALUE_1=${1:0:1}
VALUE_2=${2:0:1}
if [[ "$VALUE_1" == "$VALUE_2" ]]; then exit 0; fi
if [[ "${1:1:1}" == "${2:1:1}" ]]; then
    case $VALUE_1 in
    A | K) exit 0 ;;
    Q | J) if [[ $VALUE_2 =~ ^[JT98]$ ]]; then exit 0; fi ;;
    T) if [[ $VALUE_2 =~ ^[98]$ ]]; then exit 0; fi ;;
    *) if [[ $((VALUE_1 - VALUE_2)) -lt 3 ]]; then exit 0; fi ;;
    esac
else
    if [[ $VALUE_1 =~ ^A[KQJT9]$|^[KQJ][QJT]$ ]]; then exit 0; fi
fi
exit 1
